### ISSUE TITLE
Router bestaat niet

### ISSUE THREAD

**Issue by matthijsvdmeulen** [mauricekoreman/nacho-react-app#10]
https://github.com/mauricekoreman/nacho-react-app/blob/07d33cd7b246d6cc5c6312f32d7cb372a8c9405b/ns-react/src/App.js#L3

react-router-dom heeft 2 routers, een HashRouter en BrowserRouter, alleen Router bestaat niet, wel kun je je code beter leesbaar maken door de BrowserRouter te hernoemen in de import, dit doe je door
```javascript
import { BrowserRouter as Router } from "react-router-dom";
```
te doen

hierna kun je overige imports van react-router-dom er gewoon met komma's achter zetten
```javascript
import { BrowserRouter as Router, Route } from "react-router-dom";
```

hierna moet je natuurlijk de BrowserRouter vervangen door Router
https://github.com/mauricekoreman/nacho-react-app/blob/07d33cd7b246d6cc5c6312f32d7cb372a8c9405b/ns-react/src/App.js#L19-L26

**Comment by Veracompagnr** [comment]
dit hebben we aangepast naar:
<Router>
      <div>
        <Switch>
          <Route path="/language" component={LanguagePage} />
          <Route path="/error" component={ErrorPage} />
          <Route path="/contact" component={Contact} />
          <Route path="/sightseeing" component={SightSeeingPage} />
          <Route path="/offer" component={CityOfferPage} />
          <Route path="/Gps" component={GpsComponent} />
          <Route path="/home" component={Home} />
        </Switch>
      </div>
    </Router>
