### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by ZvanBercum** [mauricekoreman/nacho-react-app#5]
https://github.com/mauricekoreman/nacho-react-app/blob/07d33cd7b246d6cc5c6312f32d7cb372a8c9405b/ns-react/src/components/CityOfferPage.js#L5

Hier kan een aparte CSS file  voor worden gemaakt

**Comment by Veracompagnr** [comment]
Dit hebben we aangepast. We hebben de hele component aangepast
