### ISSUE TITLE
Move img files out of public folder

### ISSUE THREAD

**Issue by matthijsvdmeulen** [mauricekoreman/nacho-react-app#6]
Afbeeldingen die in de public map staan worden bij het uiteindelijke deployen (Naar een server) niet meegenomen, deze moet je in je src map plaatsen, op eenzelfde manier als css. Uitleg vind je onder deze link:
https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files

(Mijn suggestie is om de img map naar de src map te verplaatsen, en de references aan te passen

**Comment by Veracompagnr** [comment]
Hebben we aangepast
