### ISSUE TITLE
CSS -> BEM CSS

### ISSUE THREAD

**Issue by ZvanBercum** [mauricekoreman/nacho-react-app#7]
Bij alle CSS files kan de naming conventie aangepast worden naar BEM.
http://getbem.com/introduction/

Denk aan het minder gebruiken van IDs, en het benoemen van de elementen.

Misschien is het makkelijker om dan ook SCSS te gaan gebruiken? :)
https://sass-lang.com/

**Comment by Veracompagnr** [comment]
Dit hebben we aangepast en sass toe gepast. We zijn nog wel steeds bezig dit nog beter te maken.
