### ISSUE TITLE
Verander div tag in router naar switch

### ISSUE THREAD

**Issue by matthijsvdmeulen** [mauricekoreman/nacho-react-app#8]
https://github.com/mauricekoreman/nacho-react-app/blob/07d33cd7b246d6cc5c6312f32d7cb372a8c9405b/ns-react/src/App.js#L20

Om te zorgen dat je geen rare behaviour krijgt met routes, is het een goed idee om deze div te vervangen door een switch.

**Comment by Veracompagnr** [comment]
hebben we aangepast
